[versions]
agp = "8.13.2"
androidx-activity = "1.12.2"
androidx-lifecycle = "2.9.6"
composeHotReload = "1.0.0"
composeMultiplatform = "1.9.3"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
ktlint = "14.0.1"
kotlinx-datetime = "0.7.1"
kotlinSerializationJson = "1.9.0"
navigationComposeMultiplatform = "2.9.1"
koinVersion = "4.1.1"
room = "2.8.4"
sqlite = "2.6.2"
ksp = "2.3.3"
datasSoreVersion = "1.2.0"
facebookSdk = "18.1.3"

android-minSdk = "26"
android-compileSdk = "36"
android-targetSdk = "36"
[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

# Compose Multiplatform Navigation
compose-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigationComposeMultiplatform" }

# Serialization
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }

# Room (KMP)
androidx-sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

# DateTime
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

# Koin
koinBom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koinVersion" }
koinAndroid = { group = "io.insert-koin", name = "koin-android" }
koinCore = { group = "io.insert-koin", name = "koin-core" }
koinCompose = { group = "io.insert-koin", name = "koin-compose" }
koinComposeViewModel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }

# Data Store
dataStore = { module = "androidx.datastore:datastore", version.ref = "datasSoreVersion" }
dataStore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datasSoreVersion" }

# Facebook SDK
facebook-sdk-android = { group = "com.facebook.android", name = "facebook-android-sdk", version.ref = "facebookSdk" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = "androidx.room", version.ref = "room" }

bibleplanner-kotlinMultiplatform = { id = "bibleplanner.kotlin.multiplatform" }
bibleplanner-composeMultiplatform = { id = "bibleplanner.kotlin.composeMultiplatform" }
